name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed


jobs:

  build:

    runs-on: cd1

env:
  # BUCKET_NAME : "BUCKET-NAME"
  AWS_REGION : "ap-south-1"
  AWS_ACCOUNT: 739275441922
# permission can be added at job level or workflow level
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  runAWSCommands:
    runs-on: ubuntu-latest
  # This is required for actions/checkout
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::739275441922:role/2195618-GITHUB-OIDC-ROLE
          # role-session-name: samplerolesession
          aws-region: ${{ env.AWS_REGION }}

    
    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Pull Docker image
      run: sudo docker pull supdude/cicd-pipeline:latest


    #- name: Delete Old docker container
    #  run: sudo docker rm -f cicd-pipeline-container || true
    #- name: Run Docker Container
    #  run: sudo docker run -d -p 8080:8080 --name cicd-pipeline-container supdude/cicd-pipeline
